export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOG_OUT = 'LOG_OUT';

export const GET_URL_BY_URL_REQUEST = 'GET_URL_BY_URL_REQUEST';
export const GET_URL_BY_URL_SUCCESS = 'GET_URL_BY_URL_SUCCESS';
export const GET_URL_BY_URL_FAILURE = 'GET_URL_BY_URL_FAILURE';

export const GET_URL_BY_ID_REQUEST = 'GET_URL_BY_ID_REQUEST';
export const GET_URL_BY_ID_SUCCESS = 'GET_URL_BY_ID_SUCCESS';
export const GET_URL_BY_ID_FAILURE = 'GET_URL_BY_ID_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const URL_VOTE_REQUEST = 'URL_VOTE_REQUEST';
export const URL_VOTE_SUCCESS = 'URL_VOTE_SUCCESS';
export const URL_VOTE_FAILURE = 'URL_VOTE_FAILURE';
